INSERT OR IGNORE INTO TunisianSessionType (id, code, nameAr) VALUES ('RlLrXaZlkz9zU5Eg', 1, 'دروس عادية');
INSERT OR IGNORE INTO TunisianSessionType (id, code, nameAr) VALUES ('R5FtqnRJy-xJrFXM', 2, 'أشغال تطبيقية علوم ط');
INSERT OR IGNORE INTO TunisianSessionType (id, code, nameAr) VALUES ('Z9iDk5LnymlQ4lhW', 3, 'أشغال تطبيقية فيزياء');
INSERT OR IGNORE INTO TunisianSessionType (id, code, nameAr) VALUES ('acgEoa754ATFEd3S', 4, 'أشغال تطبيقية تقنية');
INSERT OR IGNORE INTO TunisianSessionType (id, code, nameAr) VALUES ('KFwvMkNKjm92jx5t', 5, 'دروس تربية بدنية');
INSERT OR IGNORE INTO TunisianSessionType (id, code, nameAr) VALUES ('8RTxXE8qjgQT_KwK', 6, 'أشغال تطبيقية إعلامية');
INSERT OR IGNORE INTO TunisianSessionType (id, code, nameAr) VALUES ('vi7anFB4Cn1HAZlE', 7, 'أشغال آلية');
INSERT OR IGNORE INTO TunisianSessionType (id, code, nameAr) VALUES ('FMAZqklTlHHWK8xY', 8, 'أشغال كهرباء');
INSERT OR IGNORE INTO TunisianSubject (id, code, nameAr, sessionTypeCode) VALUES ('0apUWrjG7GvwcGiW', 'إعلامية', 'إعلامية', 6);
INSERT OR IGNORE INTO TunisianSubject (id, code, nameAr, sessionTypeCode) VALUES ('lVTNv9eBQNm1x26e', 'إخ.رياضي', 'الإختصاص الرياضي', 5);
INSERT OR IGNORE INTO TunisianSubject (id, code, nameAr, sessionTypeCode) VALUES ('-OT85HCYF3Pz-fR-', 'الإقتصاد', 'الإقتصاد', 1);
INSERT OR IGNORE INTO TunisianSubject (id, code, nameAr, sessionTypeCode) VALUES ('kLwlJqZ3TAWYvXp_', 'الأنظمة والشبك', 'الأنظمة والشبكات', 6);
INSERT OR IGNORE INTO TunisianSubject (id, code, nameAr, sessionTypeCode) VALUES ('ZFm59Q31I10RN2Ep', 'الإيطالية', 'الإيطالية', 1);
INSERT OR IGNORE INTO TunisianSubject (id, code, nameAr, sessionTypeCode) VALUES ('TK4pN5pwXTqq-x_A', 'البرمجة', 'البرمجة', 6);
INSERT OR IGNORE INTO TunisianSubject (id, code, nameAr, sessionTypeCode) VALUES ('9hPeX6hyc6K1hsvp', 'التا و الجغ', 'التاريخ و التاريخ', 1);
INSERT OR IGNORE INTO TunisianSubject (id, code, nameAr, sessionTypeCode) VALUES ('GTJyrxUkj4FDxpsF', 'التاريخ', 'التاريخ', 1);
INSERT OR IGNORE INTO TunisianSubject (id, code, nameAr, sessionTypeCode) VALUES ('SXFDgGPSDFuz6y3m', 'ت.تقنية', 'التربية التقنية', 4);
INSERT OR IGNORE INTO TunisianSubject (id, code, nameAr, sessionTypeCode) VALUES ('N4AlUzhC4QjTIWa5', 'التصرف', 'التصرف', 1);
INSERT OR IGNORE INTO TunisianSubject (id, code, nameAr, sessionTypeCode) VALUES ('vbIV47utOI1skBTP', 'الخوارزميات', 'الخوارزميات', 6);
INSERT OR IGNORE INTO TunisianSubject (id, code, nameAr, sessionTypeCode) VALUES ('dJL9L7rzXB4DbaDR', 'الروسية', 'الروسية', 1);
INSERT OR IGNORE INTO TunisianSubject (id, code, nameAr, sessionTypeCode) VALUES ('HzeHYIx8rlIBuNUa', 'الصينية', 'الصينية', 1);
INSERT OR IGNORE INTO TunisianSubject (id, code, nameAr, sessionTypeCode) VALUES ('Sa6V0eH_3wHB8R-W', 'الفلسفة', 'الفلسفة', 1);
INSERT OR IGNORE INTO TunisianSubject (id, code, nameAr, sessionTypeCode) VALUES ('DPMDhcshEM64l9L8', 'انقليزية', 'انقليزية', 1);
INSERT OR IGNORE INTO TunisianSubject (id, code, nameAr, sessionTypeCode) VALUES ('hU9jk7MIushn7CpO', 'الجغرافيا', 'الجغرافيا', 1);
INSERT OR IGNORE INTO TunisianSubject (id, code, nameAr, sessionTypeCode) VALUES ('uCOGUtyozAJdFedi', 'ت.إسلامية', 'تربية إسلامية', 1);
INSERT OR IGNORE INTO TunisianSubject (id, code, nameAr, sessionTypeCode) VALUES ('7gxCANLKZqIF33Fr', 'ت.بدنية', 'تربية بدنية', 5);
INSERT OR IGNORE INTO TunisianSubject (id, code, nameAr, sessionTypeCode) VALUES ('PV_QOLepybIj3NjA', 'ت.تكنولوجية', 'تربية تكنولوجية', 4);
INSERT OR IGNORE INTO TunisianSubject (id, code, nameAr, sessionTypeCode) VALUES ('55hnlqHhLWub_mya', 'ت.مدنية', 'تربية مدنية', 1);
INSERT OR IGNORE INTO TunisianSubject (id, code, nameAr, sessionTypeCode) VALUES ('8yWHoPdVrZX8zDjy', 'ت.مسرحية', 'تربية مسرحية', 1);
INSERT OR IGNORE INTO TunisianSubject (id, code, nameAr, sessionTypeCode) VALUES ('6aaBIuRlLge0BnaX', 'ت.تشكيلية', 'تربية تشكيلية', 1);
INSERT OR IGNORE INTO TunisianSubject (id, code, nameAr, sessionTypeCode) VALUES ('m-5dLiaBsuE9M5y1', 'ت.موسيقية', 'تربية موسيقية', 1);
INSERT OR IGNORE INTO TunisianSubject (id, code, nameAr, sessionTypeCode) VALUES ('KFM93wsE560zeDH0', 'تك.المعلومات', 'تكنلوجيا المعلومات', 6);
INSERT OR IGNORE INTO TunisianSubject (id, code, nameAr, sessionTypeCode) VALUES ('VlPCHsj3_JxtMy2t', 'رياضيات', 'رياضيات', 1);
INSERT OR IGNORE INTO TunisianSubject (id, code, nameAr, sessionTypeCode) VALUES ('4hvESKNdU-me9O5S', 'رياضيات إخ', 'رياضيات إختيارية', 1);
INSERT OR IGNORE INTO TunisianSubject (id, code, nameAr, sessionTypeCode) VALUES ('s9u-VZqwJ4jrjgXf', 'ع.الح.و.الأرض', 'علوم الحياة و الأرض', 2);
INSERT OR IGNORE INTO TunisianSubject (id, code, nameAr, sessionTypeCode) VALUES ('4tBRoMMn_yeDNDWx', 'ع.فيزيائية', 'علوم فيزيائية', 2);
INSERT OR IGNORE INTO TunisianSubject (id, code, nameAr, sessionTypeCode) VALUES ('RC6iYGsM86SgPxbE', 'ع.الحياة اختيا', 'علوم الحياة اختيارية', 2);
INSERT OR IGNORE INTO TunisianSubject (id, code, nameAr, sessionTypeCode) VALUES ('Hgb-qDK0cpJlQ3fn', 'عربية', 'عربية', 1);
INSERT OR IGNORE INTO TunisianSubject (id, code, nameAr, sessionTypeCode) VALUES ('b2YadmR1kizQ3GiJ', 'ع.بيولوجية', 'علوم بيولوجية', 2);
INSERT OR IGNORE INTO TunisianSubject (id, code, nameAr, sessionTypeCode) VALUES ('c_LUXS7LJmY6SM2P', 'فرنسية', 'فرنسية', 1);
INSERT OR IGNORE INTO TunisianSubject (id, code, nameAr, sessionTypeCode) VALUES ('cwx12djFWE8NiIG7', 'ق,البيانات', 'قواعد البيانات', 6);
INSERT OR IGNORE INTO TunisianSubject (id, code, nameAr, sessionTypeCode) VALUES ('OsNvGnL9qDkGeuRh', 'ه.آلية', 'هندسة آلية', 7);
INSERT OR IGNORE INTO TunisianSubject (id, code, nameAr, sessionTypeCode) VALUES ('FxYzXB6W58NPj5kI', 'ه.كهربائية', 'هندسة كهربائية', 8);
INSERT OR IGNORE INTO TunisianGradeLevel (id, code, nameAr) VALUES ('M_D28ANMuZc9Su1n', '7أ', 'السابعة أساسي');
INSERT OR IGNORE INTO TunisianGradeLevel (id, code, nameAr) VALUES ('WTlWYMg_gCrzsnFN', '8أ', 'الثامنة أساسي');
INSERT OR IGNORE INTO TunisianGradeLevel (id, code, nameAr) VALUES ('gaLWEnTqbngp0iHd', '9أ', 'التاسعة أساسي');
INSERT OR IGNORE INTO TunisianGradeLevel (id, code, nameAr) VALUES ('N--JcpLopDdqnZJt', '1ث', 'الأولى ثانوي');
INSERT OR IGNORE INTO TunisianGradeLevel (id, code, nameAr) VALUES ('WH4y94qN_3q1XV46', '1ريا', 'الأولى رياضة');
INSERT OR IGNORE INTO TunisianGradeLevel (id, code, nameAr) VALUES ('8dM61CpqwfcAouhi', '2ريا', 'الثانية رياضة');
INSERT OR IGNORE INTO TunisianGradeLevel (id, code, nameAr) VALUES ('yIYjMNjtOJCkYi-d', '2آ', 'الثانية آداب');
INSERT OR IGNORE INTO TunisianGradeLevel (id, code, nameAr) VALUES ('9IOO6DP6-MdDn2E0', '2ع', 'الثانية علوم');
INSERT OR IGNORE INTO TunisianGradeLevel (id, code, nameAr) VALUES ('91Z_HwcyPK1Bdlil', '2إق', 'الثانية إقتصاد');
INSERT OR IGNORE INTO TunisianGradeLevel (id, code, nameAr) VALUES ('Q7R2ZXoOEsQteT5c', '2تك', 'الثانية تكنولوجيا الإعلامية');
INSERT OR IGNORE INTO TunisianGradeLevel (id, code, nameAr) VALUES ('cIYagp1rfPblTcat', '3ريا', 'الثالثة رياضة');
INSERT OR IGNORE INTO TunisianGradeLevel (id, code, nameAr) VALUES ('EIooMLvF4ilEVrdw', '3آ', 'الثالثة آداب');
INSERT OR IGNORE INTO TunisianGradeLevel (id, code, nameAr) VALUES ('5VcBJkQTqE3cPZeO', '3ع', 'الثالثة علوم');
INSERT OR IGNORE INTO TunisianGradeLevel (id, code, nameAr) VALUES ('Mo6ROy5bn0bmBG5B', '3إق', 'الثالثة إقتصاد');
INSERT OR IGNORE INTO TunisianGradeLevel (id, code, nameAr) VALUES ('JJgoI2uAyM-CKf7A', '3ر', 'الثالثة رياضيات');
INSERT OR IGNORE INTO TunisianGradeLevel (id, code, nameAr) VALUES ('ij17kpKFpy30rHFb', '3تق', 'الثالثة علوم تقنية');
INSERT OR IGNORE INTO TunisianGradeLevel (id, code, nameAr) VALUES ('bpo7s1oHZgsFtPXo', '3ع إ', 'الثالثة علوم الإعلامية');
INSERT OR IGNORE INTO TunisianGradeLevel (id, code, nameAr) VALUES ('c681NnGtuvPYcNp9', '4ريا', 'الرابعة رياضة');
INSERT OR IGNORE INTO TunisianGradeLevel (id, code, nameAr) VALUES ('CD0C13xSoMza4pkM', '4آ', 'الرابعة آداب');
INSERT OR IGNORE INTO TunisianGradeLevel (id, code, nameAr) VALUES ('_Wm-h98XzLagTC86', '4ع', 'الرابعة علوم تجريبية');
INSERT OR IGNORE INTO TunisianGradeLevel (id, code, nameAr) VALUES ('kv_pbuxwQUcP5ACX', '4إق', 'الرابعة إقتصاد');
INSERT OR IGNORE INTO TunisianGradeLevel (id, code, nameAr) VALUES ('9aKMoRvdy-UhYRV1', '4ر', 'الرابعة رياضيات');
INSERT OR IGNORE INTO TunisianGradeLevel (id, code, nameAr) VALUES ('7S2mY8AEX8lCB3wO', '4تق', 'الرابعة علوم تقنية');
INSERT OR IGNORE INTO TunisianGradeLevel (id, code, nameAr) VALUES ('WUqmSU9H7ZkT47lS', '4ع إ', 'الرابعة علوم الإعلامية');
